name: I have problems

on:
  push:
    branches: "main"


jobs:

  job1:

    runs-on: ubuntu-latest

    steps:
        - uses: actions/checkout@v4

        - name: Run a one-line script
          run: echo Hello, world!

  job2:

            runs-on: ubuntu-latest
            
            steps:
                needs: 
                    - job1
                - uses: actions/checkout@v4
        
                - name: Run a one-line script
                  run: echo Hello, world!