name: CI Workflow with Actions and Shell Commands

on: 
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code                    # Step using a GitHub action
        uses: actions/checkout@v2

      - name: Set up Node.js                   # Another action to set up Node.js environment
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies             # Step using a shell command
        run: npm install                       # Installs dependencies using npm

      - name: Build the project                # Another shell command
        run: npm run build                     # Runs the project's build script

  test:
    runs-on: ubuntu-latest
    needs: build                               # Dependent on the 'build' job completing
    steps:
      - name: Checkout code                    # Uses an action to check out the code
        uses: actions/checkout@v2

      - name: Set up Node.js                   # Sets up the Node.js environment
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies             # Uses a shell command to install dependencies
        run: npm install

      - name: Run tests                        # Uses a shell command to run tests
        run: npm test
