name: Conditional Steps Workflow

on: 
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

          # Runs a set of commands using the runners shell
      - name: from main brnach only
        if: github.ref == 'refs/heads/main'
        run: |
            echo Add other actions to build,
            echo test, and deploy your project.

      - name: from any branch
        run: |
            echo test from all the branches