name: Use Encrypted Secrets Example


on: 
  push:
    branches: 
      - main

jobs:
  test-secrets:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Show use of an encrypted secret
        run: |
          echo "Using the secret in a command:"
          curl http://api.weatherstack.com/current?access_key=${{ secrets.API_KEY }}"&"query=London