name: Example of Github Token Use

on: 
    push:
      branches: 
        - main

jobs:
  create-issue:
    runs-on: ubuntu-latest
    steps:
      - name: Create an Issue
        env:
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          curl -X POST \
          -H "Authorization: Bearer $TOKEN" \
          -H "Accept: application/vnd.github+json" \
          -d '{"title": "Automated Issue", "body": "This issue was created using GITHUB_TOKEN."}' \
          https://api.github.com/repos/${{ github.repository }}/issues